language: objective-c

script:
#  - xcodebuild -project ./HelloWorld/HelloWorld.xcodeproj -target HelloWorld -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -project ./HelloWorld/HelloWorld.xcodeproj -target HelloWorld -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project ./HelloWorld/HelloWorld.xcodeproj -target HelloWorld -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

